version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install awscli

  pre_build:
    commands:
      - echo "Running pre-build commands..."

  build:
    commands:
      - echo "Building index_photos Lambda function"
      - cd lambda/index_photos
      - zip -r9 ../../index_photos.zip lambda_function.py
      - cd ../..
      
      - echo "Building search_photos Lambda function"
      - cd lambda/search_photos
      - zip -r9 ../../search_photos.zip search-photos-pkg
      - cd ../..
  post_build:
    commands:
      - echo "Updating lambda Funtion..."
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://index_photos.zip
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://search_photos.zip
      - echo "DONE!"
artifacts:
  files:
    - index_photos.zip
    - search_photos.zip
    - other_scripts/dev_lambda.yml
